"""Markdown generation module."""

import re
from datetime import datetime
from pathlib import Path

from models import Paper


class MarkdownRenderer:
    """Renders papers as Markdown documents."""

    def __init__(self, output_dir: Path) -> None:
        """Initialize renderer with output directory."""
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def render(self, paper: Paper) -> Path:
        """Render paper as Markdown file."""
        filename = self._sanitize_filename(f"{paper.arxiv_id}_{paper.title[:50]}")
        output_path = self.output_dir / f"{filename}.md"

        content = self._generate_content(paper)
        output_path.write_text(content)

        return output_path

    def _sanitize_filename(self, filename: str) -> str:
        """Remove special characters from filename."""
        # Replace special chars with underscore
        sanitized = re.sub(r'[<>:"/\\|?*]', '_', filename)
        # Remove multiple spaces
        sanitized = re.sub(r'\s+', '_', sanitized)
        # Limit length
        return sanitized[:100]

    def _generate_content(self, paper: Paper) -> str:
        """Generate Markdown content."""
        lines = []

        # Title
        lines.append(f"# {paper.title}")
        lines.append("")

        # Metadata section
        lines.append("## Metadata")
        lines.append(f"- **arXiv ID**: {paper.arxiv_id}")
        lines.append(f"- **Authors**: {', '.join(paper.authors)}")
        lines.append(f"- **Submitted**: {paper.submitted_date.strftime('%Y-%m-%d')}")
        lines.append(f"- **Categories**: {', '.join(paper.categories)}")
        if paper.pdf_path:
            lines.append(f"- **PDF**: `{paper.pdf_path}`")
        lines.append(f"- **URL**: {paper.pdf_url}")
        lines.append("")

        # Abstract section
        lines.append("## Abstract")
        lines.append(paper.abstract)
        lines.append("")

        # Summary section (if available)
        if paper.summary:
            lines.append("## Summary")

            if "research_problem" in paper.summary:
                lines.append("### Research Problem")
                lines.append(paper.summary["research_problem"])
                lines.append("")

            if "core_method" in paper.summary:
                lines.append("### Core Method")
                lines.append(paper.summary["core_method"])
                lines.append("")

            if "contributions" in paper.summary:
                lines.append("### Contributions")
                for contribution in paper.summary["contributions"]:
                    lines.append(f"- {contribution}")
                lines.append("")

            if "experiments" in paper.summary:
                lines.append("### Experiments")
                lines.append(paper.summary["experiments"])
                lines.append("")

            if "limitations" in paper.summary:
                lines.append("### Limitations")
                lines.append(paper.summary["limitations"])
                lines.append("")

            if "keywords" in paper.summary:
                lines.append("### Keywords")
                for keyword in paper.summary["keywords"]:
                    lines.append(f"- {keyword}")
                lines.append("")

            if "applicable_scenarios" in paper.summary:
                lines.append("### Applicable Scenarios")
                lines.append(paper.summary["applicable_scenarios"])
                lines.append("")
        else:
            lines.append("## Summary")
            lines.append("*No summary available.*")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by Paper Daily on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

        return "\n".join(lines)
